# Generated by Django 5.0.4 on 2024-05-14 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreServicio', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('nombreEspecialista', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=254)),
                ('tipo_documento', models.CharField(choices=[('TI', 'Tarjera de identidad'), ('CC', 'Cedula'), ('PA', 'Pasaporte'), ('CE', 'Cedula extrangeria')], max_length=2)),
                ('username', models.CharField(max_length=50)),
                ('foto', models.ImageField(default='fotos/default.png', upload_to='fotos/')),
                ('rol', models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('SECRE', 'Secretaria'), ('ESPEC', 'Especialista'), ('USUAR', 'Usuario')], default='USUAR', max_length=5, null=True)),
                ('email', models.EmailField(default='iianpsdd@gmail.com', max_length=254, unique=True)),
                ('token', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolucion', models.TextField()),
                ('diagnostico', models.TextField()),
                ('observaciones', models.TextField()),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='CitaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.servicio')),
                ('idUsuarioServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticiones', models.IntegerField()),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Cancelada'), ('A', 'Admitida')], default='P', max_length=1)),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.servicio')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuario')),
            ],
        ),
    ]
