# Generated by Django 5.0.3 on 2024-10-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_alter_reserva_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('servicio', 'fecha', 'hora')},
        ),
    ]
