# Generated by Django 5.0.3 on 2024-11-26 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_alter_reserva_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='especialista',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='especialista_historia', to='aplicacion.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_historia', to='aplicacion.usuario'),
        ),
    ]
