# Generated by Django 5.0.3 on 2024-11-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_historiaclinica_especialista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='fecha_reserva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='reserva_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
