# Generated by Django 5.0.3 on 2024-11-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_historiaclinica_fecha_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('A', 'Atendida'), ('N', 'No atendida'), ('C', 'Cancelada')], default='N', max_length=1),
        ),
    ]
