# Generated by Django 5.0.3 on 2024-11-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='usuario_cancelacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Atendida'), ('N', 'No atendida'), ('C', 'Cancelada')], default='P', max_length=1),
        ),
    ]
